compute_environment: LOCAL_MACHINE
distributed_type: FSDP
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: null
num_processes: null
gpu_ids: 0,1,2,3,4,5,6,7
use_cpu: false