compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_multinode_launcher: standard
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero3_save_16bit_model: false
  zero_stage: 0
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_config: {}
fsdp_config: {}
machine_rank: 0  # will be covered
main_training_function: main
megatron_lm_config: {}
num_machines: 4  # will be covered
num_processes: 32  # will be covered
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
